server:
  port: 8080
  forward-headers-strategy: framework

  servlet:
    session:
      cookie:
        http-only: true
        secure: ${COOKIE_SECURE:false}
        same-site: lax
        path: /

spring:
  application:
    name: security-gateway

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - bbd-claims

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  spring:
    cloud:
      gateway:
        server:
          webmvc:
            routes:
              - id: user-service
                uri: ${USER_SERVICE_URI}
                predicates:
                  - Path=/api/v1/users/**,/api/v2/users/**

              - id: user-service-swagger
                uri: ${USER_SERVICE_URI}
                predicates:
                  - Path=/user/swagger-ui/**,/user/swagger-ui.html,/user/v3/api-docs/**
                filters:
                  - StripPrefix=1


              - id: item-service
                uri: ${ITEM_SERVICE_URI}
                predicates:
                  - Path=/api/v1/items/**,/api/v2/items/**

              - id: item-service-swagger
                uri: ${ITEM_SERVICE_URI}
                predicates:
                  - Path=/item/swagger-ui/**,/item/swagger-ui.html,/item/v3/api-docs/**
                filters:
                  - StripPrefix=1


              - id: inventory-service
                uri: ${INVENTORY_SERVICE_URI}
                predicates:
                  - Path=/api/v1/inventory/**,/api/v2/inventory/**

              - id: inventory-service-swagger
                uri: ${INVENTORY_SERVICE_URI}
                predicates:
                  - Path=/inventory/swagger-ui/**,/inventory/swagger-ui.html,/inventory/v3/api-docs/**
                filters:
                  - StripPrefix=1


              - id: procurement-service
                uri: ${PROCUREMENT_SERVICE_URI}
                predicates:
                  - Path=/api/v1/procurements/**,/api/v2/procurements/**

              - id: procurement-service-swagger
                uri: ${PROCUREMENT_SERVICE_URI}
                predicates:
                  - Path=/procurement/swagger-ui/**,/procurement/swagger-ui.html,/procurement/v3/api-docs/**
                filters:
                  - StripPrefix=1


              - id: sales-service
                uri: ${SALES_SERVICE_URI}
                predicates:
                  - Path=/api/v1/sales/**,/api/v2/sales/**
                filters:
                  - PrefixPath=/sales

              - id: sales-service-swagger
                uri: ${SALES_SERVICE_URI}
                predicates:
                  - Path=/sales/swagger-ui/**,/sales/swagger-ui.html,/sales/v3/api-docs/**
                filters:
                  - StripPrefix=1
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG