server:
  port: 8080
  forward-headers-strategy: framework

  servlet:
    session:
      cookie:
        http-only: true
        secure: ${COOKIE_SECURE:false}
        same-site: lax
        path: /

spring:
  application:
    name: security-gateway

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_ENDPOINT}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - bbd-claims

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://bbd-user:8080
              predicates:
                - Path=/api/v1/users/**,/api/v2/users/**

            - id: item-service
              uri: http://bbd-item:8080
              predicates:
                - Path=/api/v1/items/**,/api/v2/items/**

            - id: item-service-swagger
              uri: http://bbd-item:8080
              predicates:
                - Path=/item/swagger-ui/**,/item/swagger-ui.html,/item/v3/api-docs/**
              filters:
                - StripPrefix=1

            - id: inventory-service
              uri: http://bbd-inventory:8080
              predicates:
                - Path=/api/v1/inventory/**,/api/v2/inventory/**

            - id: procurement-service
              uri: http://bbd-procurement:8080
              predicates:
                - Path=/api/v1/procurements/**,/api/v2/procurements/**

            - id: sales-service
              uri: http://bbd-sales:8080
              predicates:
                - Path=/api/v1/sales/**,/api/v2/sales/**

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG