server:
  port: 8080

  servlet:
    session:
      cookie:
        secure: false
        same-site: lax

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG